"""C/C++ header renderer — generates const declarations or #define macros.

Supports:
    - `const double` (default) or `#define` output style
    - `static const` for multi-TU safety
    - Typed integers: uint32_t / int32_t / uint16_t / int16_t / uint8_t / int8_t
    - Array constants: static const int X[] = {1, 2, 3};
    - Configurable precision for doubles/floats

Output examples:

    Style "const" (default):
        static const uint32_t R_PULLUP = 4706U;  /* Ohm | I2C pull-up */
        static const double   R_SENSE  = 1.9999999999910001;  /* Ohm | Sense R */
        static const int THRESHOLDS[] = {50, 100, 150, 200, 250};  /* bar | Brake thresholds */

    Style "define":
        #define R_PULLUP  (4706U)   /* Ohm | I2C pull-up */
        #define R_SENSE   (1.9999999999910001)  /* Ohm | Sense R */
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_c_double
from consync.renderers import register


def _c_type_for_int(value: int, typed_ints: bool) -> tuple[str, str]:
    """Determine C type and suffix for an integer value.

    Returns (type_name, literal_suffix).
    """
    if not typed_ints:
        return ("int", "")

    if value < 0:
        if -128 <= value <= 127:
            return ("int8_t", "")
        elif -32768 <= value <= 32767:
            return ("int16_t", "")
        elif -2147483648 <= value <= 2147483647:
            return ("int32_t", "")
        else:
            return ("int64_t", "LL")
    else:
        if value <= 255:
            return ("uint8_t", "U")
        elif value <= 65535:
            return ("uint16_t", "U")
        elif value <= 4294967295:
            return ("uint32_t", "U")
        else:
            return ("uint64_t", "ULL")


def _c_type_for_float(value: float) -> str:
    """Determine C float type — always double for full precision."""
    return "double"


@register("c_header")
def render_c_header(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as a C/C++ header file.

    Args:
        constants: Constants to write.
        filepath: Output .h file path.
        config: Mapping config (for precision, header_guard, output_style, etc.)
    """
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")
    output_style = (config.output_style if config else kwargs.get("output_style", "const")).lower()
    static = config.static_const if config else kwargs.get("static_const", False)
    typed_ints = config.typed_ints if config else kwargs.get("typed_ints", True)

    # Determine header guard
    guard = ""
    if config and config.header_guard:
        guard = config.header_guard
    else:
        guard = filepath.stem.upper().replace("-", "_").replace(".", "_") + "_H"

    # Prefix handling
    prefix = config.prefix if config else kwargs.get("prefix", "")

    # Calculate alignment
    names = [prefix + c.name for c in constants]
    name_width = max((len(n) for n in names), default=20) + 2

    # Qualifier for const style
    qualifier = "static const" if static else "const"

    # Include for stdint types
    needs_stdint = typed_ints and any(
        isinstance(c.value, int) or
        (isinstance(c.value, list) and c.value and isinstance(c.value[0], int))
        for c in constants
    )

    # Build header
    lines = [
        "/* AUTO-GENERATED by consync — do not edit by hand.",
        f" * Source: {source_name}",
        f" * Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        " * Regenerate: consync sync",
        " */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
    ]

    if needs_stdint and output_style == "const":
        lines.append("#include <stdint.h>")
        lines.append("")

    # Build constant declarations
    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        # Build comment
        parts = [p for p in (c.unit, c.description) if p]
        comment = f"  /* {' | '.join(parts)} */" if parts else ""

        # === Array values ===
        if isinstance(c.value, list):
            _render_array_const(lines, c, name, qualifier, typed_ints, precision, comment)
            continue

        # === Scalar values ===
        # Format value and determine type
        if isinstance(c.value, int):
            c_type, suffix = _c_type_for_int(c.value, typed_ints)
            val_str = str(c.value) + suffix
        else:
            c_type = _c_type_for_float(c.value)
            val_str = format_c_double(c.value, precision)
            suffix = ""

        # Emit line based on output style
        if output_style == "define":
            lines.append(f"#define {name:<{name_width}} ({val_str}){comment}")
        else:
            type_width = max(len(_get_c_type(c2, typed_ints)) for c2 in constants
                            if not isinstance(c2.value, list))  if any(
                                not isinstance(c2.value, list) for c2 in constants) else len(c_type)
            lines.append(
                f"{qualifier} {c_type:<{type_width}} {name:<{name_width}} = {val_str};{comment}"
            )

    lines += ["", f"#endif /* {guard} */", ""]

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")


def _get_c_type(c: "Constant", typed_ints: bool) -> str:
    """Get the C type string for a scalar constant."""
    if isinstance(c.value, int):
        return _c_type_for_int(c.value, typed_ints)[0]
    return _c_type_for_float(c.value)


def _render_array_const(
    lines: list[str],
    c: "Constant",
    name: str,
    qualifier: str,
    typed_ints: bool,
    precision: int,
    comment: str,
) -> None:
    """Render an array constant as: static const int X[] = {1, 2, 3};"""

    arr = c.value
    if not arr:
        return

    first = arr[0]
    if isinstance(first, int):
        # Use typed ints based on max value in array
        max_val = max(arr)
        min_val = min(arr)
        if min_val < 0:
            c_type = _c_type_for_int(min_val, typed_ints)[0]
            # Ensure type fits max too
            if typed_ints:
                c_type2 = _c_type_for_int(max_val, typed_ints)[0]
                # Pick the wider signed type
                if "64" in c_type or "64" in c_type2:
                    c_type = "int64_t"
                elif "32" in c_type or "32" in c_type2:
                    c_type = "int32_t"
                elif "16" in c_type or "16" in c_type2:
                    c_type = "int16_t"
        else:
            c_type = _c_type_for_int(max_val, typed_ints)[0]
        vals = ", ".join(str(v) for v in arr)
    elif isinstance(first, float):
        c_type = "double"
        vals = ", ".join(format_c_double(v, precision) for v in arr)
    else:
        # String arrays → not directly supported in C, skip
        return

    lines.append(
        f"{qualifier} {c_type} {name}[] = {{{vals}}};{comment}"
    )
