"""C/C++ header renderer — generates const double declarations.

Output format:
    /* AUTO-GENERATED by consync — do not edit by hand.
     * Source: constants.xlsx
     * Synced: 2026-05-05 14:30:00
     */

    #ifndef HW_CONSTANTS_H
    #define HW_CONSTANTS_H

    const double R_SENSE         = 1.9999999999910001;  /* Ohm | Current sense resistor */
    const double R_PULLUP        = 4706;                /* Ohm | I2C pull-up resistor */

    #endif /* HW_CONSTANTS_H */
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_c_double
from consync.renderers import register


@register("c_header")
def render_c_header(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as a C header file.

    Args:
        constants: Constants to write.
        filepath: Output .h file path.
        config: Mapping config (for precision, header_guard, etc.)
    """
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")

    # Determine header guard
    guard = ""
    if config and config.header_guard:
        guard = config.header_guard
    else:
        guard = filepath.stem.upper().replace("-", "_").replace(".", "_") + "_H"

    # Prefix handling
    prefix = config.prefix if config else kwargs.get("prefix", "")

    # Calculate alignment
    names = [prefix + c.name for c in constants]
    name_width = max((len(n) for n in names), default=20) + 2

    # Build lines
    lines = [
        f"/* AUTO-GENERATED by consync — do not edit by hand.",
        f" * Source: {source_name}",
        f" * Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f" * Regenerate: consync sync",
        f" */",
        f"",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
    ]

    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        # Format value
        if isinstance(c.value, int):
            val_str = str(c.value)
        else:
            val_str = format_c_double(c.value, precision)

        # Build comment
        parts = [p for p in (c.unit, c.description) if p]
        comment = f"  /* {' | '.join(parts)} */" if parts else ""

        lines.append(f"const double {name:<{name_width}} = {val_str};{comment}")

    lines += ["", f"#endif /* {guard} */", ""]

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")
