"""C/C++ header renderer — generates const declarations or #define macros.

Supports:
    - `const double` (default) or `#define` output style
    - `static const` for multi-TU safety
    - Typed integers: uint32_t / int32_t / uint16_t / int16_t / uint8_t / int8_t
    - Configurable precision for doubles/floats

Output examples:

    Style "const" (default):
        static const uint32_t R_PULLUP = 4706U;  /* Ohm | I2C pull-up */
        static const double   R_SENSE  = 1.9999999999910001;  /* Ohm | Sense R */

    Style "define":
        #define R_PULLUP  (4706U)   /* Ohm | I2C pull-up */
        #define R_SENSE   (1.9999999999910001)  /* Ohm | Sense R */
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_c_double
from consync.renderers import register


def _c_type_for_int(value: int, typed_ints: bool) -> tuple[str, str]:
    """Determine C type and suffix for an integer value.

    Returns (type_name, literal_suffix).
    """
    if not typed_ints:
        return ("int", "")

    if value < 0:
        if -128 <= value <= 127:
            return ("int8_t", "")
        elif -32768 <= value <= 32767:
            return ("int16_t", "")
        elif -2147483648 <= value <= 2147483647:
            return ("int32_t", "")
        else:
            return ("int64_t", "LL")
    else:
        if value <= 255:
            return ("uint8_t", "U")
        elif value <= 65535:
            return ("uint16_t", "U")
        elif value <= 4294967295:
            return ("uint32_t", "U")
        else:
            return ("uint64_t", "ULL")


def _c_type_for_float(value: float) -> str:
    """Determine C float type — always double for full precision."""
    return "double"


@register("c_header")
def render_c_header(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as a C/C++ header file.

    Args:
        constants: Constants to write.
        filepath: Output .h file path.
        config: Mapping config (for precision, header_guard, output_style, etc.)
    """
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")
    output_style = (config.output_style if config else kwargs.get("output_style", "const")).lower()
    static = config.static_const if config else kwargs.get("static_const", False)
    typed_ints = config.typed_ints if config else kwargs.get("typed_ints", True)

    # Determine header guard
    guard = ""
    if config and config.header_guard:
        guard = config.header_guard
    else:
        guard = filepath.stem.upper().replace("-", "_").replace(".", "_") + "_H"

    # Prefix handling
    prefix = config.prefix if config else kwargs.get("prefix", "")

    # Calculate alignment
    names = [prefix + c.name for c in constants]
    name_width = max((len(n) for n in names), default=20) + 2

    # Include for stdint types
    needs_stdint = typed_ints and any(isinstance(c.value, int) for c in constants)

    # Build header
    lines = [
        f"/* AUTO-GENERATED by consync — do not edit by hand.",
        f" * Source: {source_name}",
        f" * Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f" * Regenerate: consync sync",
        f" */",
        f"",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
    ]

    if needs_stdint and output_style == "const":
        lines.append("#include <stdint.h>")
        lines.append("")

    # Build constant declarations
    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        # Format value and determine type
        if isinstance(c.value, int):
            c_type, suffix = _c_type_for_int(c.value, typed_ints)
            val_str = str(c.value) + suffix
        else:
            c_type = _c_type_for_float(c.value)
            val_str = format_c_double(c.value, precision)
            suffix = ""

        # Build comment
        parts = [p for p in (c.unit, c.description) if p]
        comment = f"  /* {' | '.join(parts)} */" if parts else ""

        # Emit line based on output style
        if output_style == "define":
            lines.append(f"#define {name:<{name_width}} ({val_str}){comment}")
        else:
            qualifier = "static const" if static else "const"
            type_width = max(len(c_type) for c2 in constants
                            for c_type in [_c_type_for_int(c2.value, typed_ints)[0]
                                           if isinstance(c2.value, int)
                                           else _c_type_for_float(c2.value)])
            lines.append(
                f"{qualifier} {c_type:<{type_width}} {name:<{name_width}} = {val_str};{comment}"
            )

    lines += ["", f"#endif /* {guard} */", ""]

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")
