"""C# renderer — generates a static class with typed constants.

Output example:
    // AUTO-GENERATED by consync — do not edit by hand.
    namespace HardwareConstants
    {
        public static class Constants
        {
            /// <summary>Current sense resistor (Ohm)</summary>
            public const double R_SENSE = 1.9999999999910001;

            /// <summary>I2C pull-up resistor (Ohm)</summary>
            public const uint R_PULLUP = 4706;
        }
    }
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_float
from consync.renderers import register


def _csharp_type(value: int | float | str, typed_ints: bool = True) -> tuple[str, str]:
    """Determine C# type and optional suffix for a value.

    Returns (type_name, literal_suffix).
    """
    if isinstance(value, int):
        if not typed_ints:
            return ("int", "")
        if value < 0:
            if -2147483648 <= value <= 2147483647:
                return ("int", "")
            else:
                return ("long", "L")
        else:
            if value <= 2147483647:
                return ("int", "")
            elif value <= 4294967295:
                return ("uint", "U")
            else:
                return ("ulong", "UL")
    elif isinstance(value, float):
        return ("double", "")
    else:
        return ("string", "")


@register("csharp")
def render_csharp(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as a C# static class.

    Args:
        constants: Constants to write.
        filepath: Output .cs file path.
        config: Mapping config (for precision, namespace, etc.)
    """
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")
    namespace = (config.namespace if config else kwargs.get("namespace", "")) or "Constants"
    class_name = (config.module_name if config else kwargs.get("module_name", "")) or "HwConstants"
    typed_ints = config.typed_ints if config else kwargs.get("typed_ints", True)
    prefix = config.prefix if config else kwargs.get("prefix", "")

    lines = [
        "// AUTO-GENERATED by consync — do not edit by hand.",
        f"// Source: {source_name}",
        f"// Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "// Regenerate: consync sync",
        "",
        f"namespace {namespace}",
        "{",
        f"    public static class {class_name}",
        "    {",
    ]

    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        # XML doc comment
        doc_parts = [p for p in (c.description, f"({c.unit})" if c.unit else "") if p]
        if doc_parts:
            doc = " ".join(doc_parts)
            lines.append(f"        /// <summary>{doc}</summary>")

        # === Array values ===
        if isinstance(c.value, list):
            _render_csharp_array(lines, c, name, typed_ints, precision)
            lines.append("")
            continue

        # === Scalar values ===
        cs_type, suffix = _csharp_type(c.value, typed_ints)

        # Format value
        if isinstance(c.value, int):
            val_str = str(c.value) + suffix
        elif isinstance(c.value, float):
            val_str = format_float(c.value, precision)
        else:
            val_str = f'"{c.value}"'

        lines.append(f"        public const {cs_type} {name} = {val_str};")
        lines.append("")

    # Remove trailing blank line before closing braces
    if lines and lines[-1] == "":
        lines.pop()

    lines += [
        "    }",
        "}",
        "",
    ]

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")


def _render_csharp_array(
    lines: list[str],
    c: "Constant",
    name: str,
    typed_ints: bool,
    precision: int,
) -> None:
    """Render an array constant as: public static readonly int[] X = { 1, 2, 3 };"""
    arr = c.value
    if not arr:
        return

    first = arr[0]
    if isinstance(first, int):
        cs_type = "int"
        if typed_ints:
            max_val = max(arr)
            min_val = min(arr)
            if min_val < 0:
                if min_val >= -2147483648 and max_val <= 2147483647:
                    cs_type = "int"
                else:
                    cs_type = "long"
            else:
                if max_val <= 2147483647:
                    cs_type = "int"
                elif max_val <= 4294967295:
                    cs_type = "uint"
                else:
                    cs_type = "ulong"
        vals = ", ".join(str(v) for v in arr)
    elif isinstance(first, float):
        cs_type = "double"
        vals = ", ".join(format_float(v, precision) for v in arr)
    else:
        cs_type = "string"
        vals = ", ".join(f'"{v}"' for v in arr)

    lines.append(
        f"        public static readonly {cs_type}[] {name} = {{ {vals} }};"
    )
