"""C# renderer — generates a static class with typed constants.

Output example:
    // AUTO-GENERATED by consync — do not edit by hand.
    namespace HardwareConstants
    {
        public static class Constants
        {
            /// <summary>Current sense resistor (Ohm)</summary>
            public const double R_SENSE = 1.9999999999910001;

            /// <summary>I2C pull-up resistor (Ohm)</summary>
            public const uint R_PULLUP = 4706;
        }
    }
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_float
from consync.renderers import register


def _csharp_type(value: int | float | str, typed_ints: bool = True) -> tuple[str, str]:
    """Determine C# type and optional suffix for a value.

    Returns (type_name, literal_suffix).
    """
    if isinstance(value, int):
        if not typed_ints:
            return ("int", "")
        if value < 0:
            if -2147483648 <= value <= 2147483647:
                return ("int", "")
            else:
                return ("long", "L")
        else:
            if value <= 2147483647:
                return ("int", "")
            elif value <= 4294967295:
                return ("uint", "U")
            else:
                return ("ulong", "UL")
    elif isinstance(value, float):
        return ("double", "")
    else:
        return ("string", "")


@register("csharp")
def render_csharp(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as a C# static class.

    Args:
        constants: Constants to write.
        filepath: Output .cs file path.
        config: Mapping config (for precision, namespace, etc.)
    """
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")
    namespace = (config.namespace if config else kwargs.get("namespace", "")) or "Constants"
    class_name = (config.module_name if config else kwargs.get("module_name", "")) or "HwConstants"
    typed_ints = config.typed_ints if config else kwargs.get("typed_ints", True)
    prefix = config.prefix if config else kwargs.get("prefix", "")

    lines = [
        f"// AUTO-GENERATED by consync — do not edit by hand.",
        f"// Source: {source_name}",
        f"// Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"// Regenerate: consync sync",
        f"",
        f"namespace {namespace}",
        f"{{",
        f"    public static class {class_name}",
        f"    {{",
    ]

    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        cs_type, suffix = _csharp_type(c.value, typed_ints)

        # Format value
        if isinstance(c.value, int):
            val_str = str(c.value) + suffix
        elif isinstance(c.value, float):
            val_str = format_float(c.value, precision)
        else:
            val_str = f'"{c.value}"'

        # XML doc comment
        doc_parts = [p for p in (c.description, f"({c.unit})" if c.unit else "") if p]
        if doc_parts:
            doc = " ".join(doc_parts)
            lines.append(f"        /// <summary>{doc}</summary>")

        lines.append(f"        public const {cs_type} {name} = {val_str};")
        lines.append("")

    # Remove trailing blank line before closing braces
    if lines and lines[-1] == "":
        lines.pop()

    lines += [
        f"    }}",
        f"}}",
        "",
    ]

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")
