"""Python constants renderer — generates a Python module with typed constants.

Output format:
    # AUTO-GENERATED by consync — do not edit by hand.
    # Source: constants.xlsx | Synced: 2026-05-05 14:30:00

    R_SENSE: float = 1.9999999999910001          # Ohm — Current sense resistor
    R_PULLUP: int = 4706                         # Ohm — I2C pull-up resistor
    C_FILTER: float = 4.7832940000000000e-07     # F — Input filter capacitor
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_float
from consync.renderers import register


@register("python")
def render_python(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as a Python module with type annotations."""
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")
    prefix = config.prefix if config else kwargs.get("prefix", "")

    lines = [
        f'"""AUTO-GENERATED by consync — do not edit by hand."""',
        f"# Source: {source_name} | Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"# Regenerate: consync sync",
        f"",
    ]

    # Calculate alignment
    names = [prefix + c.name for c in constants]
    max_name = max((len(n) for n in names), default=10)

    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        # Build inline comment
        parts = [p for p in (c.unit, c.description) if p]
        comment = f"  # {' — '.join(parts)}" if parts else ""

        # Format value with type annotation
        if isinstance(c.value, list):
            # Array → list[int] / list[float] / list[str]
            if c.value and isinstance(c.value[0], int):
                type_hint = "list[int]"
                val_str = repr(c.value)
            elif c.value and isinstance(c.value[0], float):
                type_hint = "list[float]"
                val_str = "[" + ", ".join(format_float(v, precision) for v in c.value) + "]"
            else:
                type_hint = "list[str]"
                val_str = repr(c.value)
        elif isinstance(c.value, int):
            type_hint = "int"
            val_str = str(c.value)
        elif isinstance(c.value, float):
            type_hint = "float"
            val_str = format_float(c.value, precision)
        else:
            type_hint = "str"
            val_str = repr(c.value)

        decl = f"{name}: {type_hint}"
        lines.append(f"{decl:<{max_name + 8}} = {val_str}{comment}")

    lines.append("")  # trailing newline

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")
