"""Rust constants renderer — generates const declarations.

Output format:
    //! AUTO-GENERATED by consync — do not edit by hand.
    //! Source: constants.xlsx | Synced: 2026-05-05 14:30:00

    /// Current sense resistor (Ohm)
    pub const R_SENSE: f64 = 1.9999999999910001;

    /// I2C pull-up resistor (Ohm)
    pub const R_PULLUP: f64 = 4706.0;
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_float
from consync.renderers import register


@register("rust")
def render_rust(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as Rust const declarations."""
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")
    prefix = config.prefix if config else kwargs.get("prefix", "")

    lines = [
        f"//! AUTO-GENERATED by consync — do not edit by hand.",
        f"//! Source: {source_name} | Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"//! Regenerate: consync sync",
        f"",
    ]

    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        # Doc comment
        parts = [p for p in (c.description, f"({c.unit})" if c.unit else "") if p]
        if parts:
            lines.append(f"/// {' '.join(parts)}")

        # Type and value
        if isinstance(c.value, int):
            type_name = "i64"
            val_str = str(c.value)
        else:
            type_name = "f64"
            val_str = format_float(c.value, precision)
            # Rust requires decimal point or scientific notation for f64 literals
            if "." not in val_str and "e" not in val_str and "E" not in val_str:
                val_str += ".0"

        lines.append(f"pub const {name}: {type_name} = {val_str};")
        lines.append("")

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")
