"""Verilog/SystemVerilog renderer — generates parameter declarations.

Output format (Verilog):
    // AUTO-GENERATED by consync — do not edit by hand.
    // Source: constants.xlsx | Synced: 2026-05-05 14:30:00

    parameter real R_SENSE         = 1.9999999999910001;  // Ohm — Current sense resistor
    parameter real R_PULLUP        = 4706.0;              // Ohm — I2C pull-up resistor
    parameter real FREQ_SWITCH     = 299872.93847293;     // Hz — Switching frequency

Output format (module wrapper):
    module design_params;
        parameter real R_SENSE = 1.9999999999910001;
        ...
    endmodule
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_float
from consync.renderers import register


@register("verilog")
def render_verilog(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as Verilog/SystemVerilog parameters."""
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")
    prefix = config.prefix if config else kwargs.get("prefix", "")
    module_name = config.module_name if config else kwargs.get("module_name", "")

    lines = [
        f"// AUTO-GENERATED by consync — do not edit by hand.",
        f"// Source: {source_name} | Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"// Regenerate: consync sync",
        f"",
    ]

    indent = ""
    if module_name:
        lines.append(f"module {module_name};")
        lines.append("")
        indent = "    "

    # Calculate alignment
    names = [prefix + c.name for c in constants]
    name_width = max((len(n) for n in names), default=20) + 2

    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        # Verilog types
        if isinstance(c.value, int):
            type_kw = "integer"
            val_str = str(c.value)
        else:
            type_kw = "real"
            val_str = format_float(c.value, precision)
            # Verilog real literals need a decimal point
            if "." not in val_str and "e" not in val_str and "E" not in val_str:
                val_str += ".0"

        # Comment
        parts = [p for p in (c.unit, c.description) if p]
        comment = f"  // {' — '.join(parts)}" if parts else ""

        lines.append(f"{indent}parameter {type_kw} {name:<{name_width}} = {val_str};{comment}")

    if module_name:
        lines.append("")
        lines.append("endmodule")

    lines.append("")

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")
