"""VHDL renderer — generates constant declarations in a package.

Output format:
    -- AUTO-GENERATED by consync — do not edit by hand.
    -- Source: constants.xlsx | Synced: 2026-05-05 14:30:00

    library ieee;
    use ieee.std_logic_1164.all;
    use ieee.math_real.all;

    package hw_constants is
        constant R_SENSE       : real := 1.9999999999910001;  -- Ohm | Current sense resistor
        constant R_PULLUP      : real := 4706.0;              -- Ohm | I2C pull-up resistor
        constant FREQ_SWITCH   : real := 299872.93847293;     -- Hz | Switching frequency
    end package hw_constants;
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from consync.models import Constant, MappingConfig
from consync.precision import format_float
from consync.renderers import register


@register("vhdl")
def render_vhdl(
    constants: list[Constant],
    filepath: str | Path,
    *,
    config: MappingConfig | None = None,
    **kwargs,
) -> None:
    """Render constants as a VHDL package."""
    filepath = Path(filepath)
    precision = config.precision if config else kwargs.get("precision", 17)
    source_name = config.source if config else kwargs.get("source", "unknown")
    prefix = config.prefix if config else kwargs.get("prefix", "")
    module_name = config.module_name if config else kwargs.get("module_name", "")

    # Package name: from module_name or derive from filename
    pkg_name = module_name or filepath.stem.replace("-", "_").replace(".", "_")

    lines = [
        "-- AUTO-GENERATED by consync — do not edit by hand.",
        f"-- Source: {source_name} | Synced: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "-- Regenerate: consync sync",
        "",
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "use ieee.math_real.all;",
        "",
        f"package {pkg_name} is",
        "",
    ]

    # Calculate alignment
    names = [prefix + c.name for c in constants]
    name_width = max((len(n) for n in names), default=20) + 2

    for c in constants:
        name = prefix + c.name
        if config and config.uppercase_names:
            name = name.upper()

        # VHDL types
        if isinstance(c.value, int):
            type_name = "integer"
            val_str = str(c.value)
        else:
            type_name = "real"
            val_str = format_float(c.value, precision)
            # VHDL real literals need a decimal point
            if "." not in val_str and "e" not in val_str and "E" not in val_str:
                val_str += ".0"

        # Comment
        parts = [p for p in (c.unit, c.description) if p]
        comment = f"  -- {' | '.join(parts)}" if parts else ""

        lines.append(
            f"    constant {name:<{name_width}} : {type_name} := {val_str};{comment}"
        )

    lines += [
        "",
        f"end package {pkg_name};",
        "",
    ]

    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines), encoding="utf-8")
